ERROR - 2025-09-08 09:53:00 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ITE311-PARCON\app\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#6 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-PARCON\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-09-08 09:53:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 09:53:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$aNpSjySLQTQzq5heG7vdn.DSJaZG3GlJsu78z72BnbyyAQNLx5Xfy\', \'user\', \'2025-09-08 09:53:00\', \'2025-09-08 09:53:00\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$aNpSjySLQTQzq5heG7vdn.DSJaZG3GlJsu78z72BnbyyAQNLx5Xfy\', \'user\', \'2025-09-08 09:53:00\', \'2025-09-08 09:53:00\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 09:53:01 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$aNpSjySLQTQzq5heG7vdn.DSJaZG3GlJsu78z72BnbyyAQNLx5Xfy\', \'user\', \'2025-09-08 09:53:00\', \'2025-09-08 09:53:00\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$aNpSjySLQTQzq5heG7vdn.DSJaZG3GlJsu78z72BnbyyAQNLx5Xfy\', \'user\', \'2025-09-08 09:53:00\', \'2025-09-08 09:53:00\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$aNpSjySLQTQzq5heG7vdn.DSJaZG3GlJsu78z72BnbyyAQNLx5Xfy\', \'user\', \'2025-09-08 09:53:00\', \'2025-09-08 09:53:00\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-08 10:02:47 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ITE311-PARCON\app\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#6 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-PARCON\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-09-08 10:02:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 10:02:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$daXMKq81n8hoR8jZzJpmEeWi94UF79ch7ISPZEI5qKnnqjWeJWHva\', \'user\', \'2025-09-08 10:02:47\', \'2025-09-08 10:02:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$daXMKq81n8hoR8jZzJpmEeWi94UF79ch7ISPZEI5qKnnqjWeJWHva\', \'user\', \'2025-09-08 10:02:47\', \'2025-09-08 10:02:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 10:02:47 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$daXMKq81n8hoR8jZzJpmEeWi94UF79ch7ISPZEI5qKnnqjWeJWHva\', \'user\', \'2025-09-08 10:02:47\', \'2025-09-08 10:02:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$daXMKq81n8hoR8jZzJpmEeWi94UF79ch7ISPZEI5qKnnqjWeJWHva\', \'user\', \'2025-09-08 10:02:47\', \'2025-09-08 10:02:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$daXMKq81n8hoR8jZzJpmEeWi94UF79ch7ISPZEI5qKnnqjWeJWHva\', \'user\', \'2025-09-08 10:02:47\', \'2025-09-08 10:02:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-08 12:03:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'lms_parcon', 3306, '', 0)
#1 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ITE311-PARCON\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-PARCON\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('lorenzo@sample....', 'users.email', Array)
#6 C:\xampp\htdocs\ITE311-PARCON\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('lorenzo@sample....', 'users.email', Array, NULL, 'email')
#7 C:\xampp\htdocs\ITE311-PARCON\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'email', 'lorenzo@sample....', Array, Array, 'email')
#8 C:\xampp\htdocs\ITE311-PARCON\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#9 C:\xampp\htdocs\ITE311-PARCON\app\Controllers\Auth.php(65): CodeIgniter\Controller->validate(Array, Array)
#10 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#11 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#15 C:\xampp\htdocs\ITE311-PARCON\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ITE311-PARCON\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ITE311-PARCON\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('lorenzo@sample....', 'users.email', Array)
#5 C:\xampp\htdocs\ITE311-PARCON\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('lorenzo@sample....', 'users.email', Array, NULL, 'email')
#6 C:\xampp\htdocs\ITE311-PARCON\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'email', 'lorenzo@sample....', Array, Array, 'email')
#7 C:\xampp\htdocs\ITE311-PARCON\system\Controller.php(138): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\ITE311-PARCON\app\Controllers\Auth.php(65): CodeIgniter\Controller->validate(Array, Array)
#9 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ITE311-PARCON\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-09-08 12:03:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('lorenzo@sample.com', 'users.email', [...])
 5 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('lorenzo@sample.com', 'users.email', [...], null, 'email')
 6 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'email', 'lorenzo@sample.com', [...], [...], 'email')
 7 SYSTEMPATH\Controller.php(138): CodeIgniter\Validation\Validation->run()
 8 APPPATH\Controllers\Auth.php(65): CodeIgniter\Controller->validate([...], [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-08 12:04:35 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-PARCON\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ITE311-PARCON\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ITE311-PARCON\app\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#6 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-PARCON\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-PARCON\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-PARCON\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-09-08 12:04:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 12:04:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$b59QDqSHPxPOFIp5hA5AiuKdugOCBRSh1.ZX/uzkwSd8Dtjw8KJiW\', \'user\', \'2025-09-08 12:04:35\', \'2025-09-08 12:04:35\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$b59QDqSHPxPOFIp5hA5AiuKdugOCBRSh1.ZX/uzkwSd8Dtjw8KJiW\', \'user\', \'2025-09-08 12:04:35\', \'2025-09-08 12:04:35\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 12:04:35 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$b59QDqSHPxPOFIp5hA5AiuKdugOCBRSh1.ZX/uzkwSd8Dtjw8KJiW\', \'user\', \'2025-09-08 12:04:35\', \'2025-09-08 12:04:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$b59QDqSHPxPOFIp5hA5AiuKdugOCBRSh1.ZX/uzkwSd8Dtjw8KJiW\', \'user\', \'2025-09-08 12:04:35\', \'2025-09-08 12:04:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Cris Lorenzo\', \'lorenzo@sample.com\', \'$2y$10$b59QDqSHPxPOFIp5hA5AiuKdugOCBRSh1.ZX/uzkwSd8Dtjw8KJiW\', \'user\', \'2025-09-08 12:04:35\', \'2025-09-08 12:04:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Controllers\Auth.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
